basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# TEMPLATE URLs
app_name = 'basic_app'

urlpatterns =[
    url(r'^$', views.index, name = 'index'),
    url(r'^info/', views.info, name = 'info'),
    url(r'^signup/', views.register, name = 'signup'),
    url(r'^news/', views.news, name = 'news'),
    url(r'^national_rankings/', views.natl_rank, name = 'natl_rank'),
    url(r'^my_recruits/', views.my_recruits, name = 'my_recruits'),
    url(r'^upcoming_events/', views.upcoming, name = 'upcoming'),
    url(r'^manage_staff/', views.manage_staff, name = 'manage_staff'),
    url(r'^social_media/', views.manage_social, name = 'manage_social'),
    url(r'^login/', views.user_login, name = 'login'),
]

bluechiphoops/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('basic_app.urls',namespace="basic_app")),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
# class UserProfileInfo(models.Model):
#     user = models.OneToOneField(User)
#
#     #additional classes
#
#     portfolio_site = models.URLField(blank=True)
#
#     profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User)
    first_name = models.CharField(max_length = 40)
    last_name = models.CharField(max_length = 40)
    def __str__(self):
        return self.user.username

class RecruitProfileInfo(models.Model):
    player_grad_year = models.IntegerField()
    player_first_name = models.CharField(max_length = 40)
    player_last_name = models.CharField(max_length = 40)
    player_position = models.CharField(max_length = 5)
    player_height = models.CharField(max_length = 5)
    player_weight = models.IntegerField()
    player_school = models.CharField(max_length = 40)
    player_state = models.CharField(max_length = 2)
    # player_phone = models.PhoneNumberField(blank = True)
    player_phone = models.CharField( max_length = 15, blank = True)
    player_twitter = models.CharField(max_length = 40, blank = True)

    def __str__(self):
        return self.user.username

class NationalRecruitList(models.Model):

    player_grad_year = models.IntegerField()
    player_rivals_rank = models.IntegerField()
    player_espn_rank = models.IntegerField()
    player_first_name = models.CharField(max_length = 40)
    player_last_name = models.CharField(max_length = 40)
    player_position = models.CharField(max_length = 5)
    player_school = models.CharField(max_length = 40)
    player_state = models.CharField(max_length = 2)
    player_height = models.CharField(max_length = 5)
    player_weight = models.IntegerField()
    player_potential_schools = models.CharField(max_length = 260)

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo, RecruitProfileInfo, NationalRecruitList

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        # fields = ('username','email', 'password')
        fields = ('email', 'password')

class UserProfileInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('first_name', 'last_name')

class RecruitProfileInfoForm(forms.ModelForm):
    class Meta():
        model = RecruitProfileInfo
        fields = ('player_grad_year', 'player_first_name', 'player_last_name',
        'player_position', 'player_height', 'player_weight', 'player_school',
        'player_state', 'player_phone', 'player_twitter')

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfo, RecruitProfileInfoForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

def info(request):
    return render(request, 'basic_app/info.html')

def register(request):
    # registered = False
    # if request.method == "POST":
    #     user_form = UserForm(data = request.POST)
    #     if user_form.is_valid():
    #         user = user_form.save()
    #         create = User.objects.create()
    #         create.email = user.email
    #         create.password = user.password
    #         create.username = user.email
    #         create.save()
    #         # user.set_password(user.password)
    #         # user.save()
    #         registered = True
    # else:
    #     user_form = UserForm()
    #     profile_form = UserProfileInfo()
    # return render(request, 'basic_app/signup.html', {'user_form':user_form, 'registered':registered, 'profile_form':profile_form})

    registered=False
    if request.method =='POST':
        user_form =UserForm(data=request.POST)
        profile_form=UserProfileInfo(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user
            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfo()

    return render(request,'basic_app/signup.html',
            {'user_form':user_form,'profile_form':profile_form,
            'registered':registered})

def news(request):
    return render(request, 'basic_app/news.html')

def natl_rank(request):
    return render(request, 'basic_app/natl_ranks.html')

def my_recruits(request):
    return render(request, "basic_app/my_recruits.html")

def upcoming(request):
    return render(request, "basic_app/upcoming.html")

def manage_staff(request):
    return render(request, "basic_app/staff.html")

def manage_social(request):
    return render(request, "basic_app/social.html")

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('home_page:index'))

# def register(request):
#
#     registered = False
#
#     if request.method == 'POST':
#
#         # Get info from "both" forms
#         # It appears as one form to the user on the .html page
#         user_form = UserForm(data=request.POST)
#         profile_form = UserProfileInfoForm(data=request.POST)
#
#         # Check to see both forms are valid
#         if user_form.is_valid() and profile_form.is_valid():
#
#             # Save User Form to Database
#             user = user_form.save()
#
#             # Hash the password
#             user.set_password(user.password)
#
#             # Update with Hashed password
#             user.save()
#
#             # Now we deal with the extra info!
#
#             # Can't commit yet because we still need to manipulate
#             profile = profile_form.save(commit=False)
#
#             # Set One to One relationship between
#             # UserForm and UserProfileInfoForm
#             profile.user = user
#
#             # Check if they provided a profile picture
#             if 'profile_pic' in request.FILES:
#                 print('found it')
#                 # If yes, then grab it from the POST form reply
#                 profile.profile_pic = request.FILES['profile_pic']
#
#             # Now save model
#             profile.save()
#
#             # Registration Successful!
#             registered = True
#
#         else:
#             # One of the forms was invalid if this else gets called.
#             print(user_form.errors,profile_form.errors)
#
#     else:
#         # Was not an HTTP post so we just render the forms as blank.
#         user_form = UserForm()
#         profile_form = UserProfileInfoForm()
#
#     # This is the render and context dictionary to feed
#     # back to the registration.html file page.
#     return render(request,'basic_app/signup.html',
#                           {'user_form':user_form,
#                            'profile_form':profile_form,
#                            'registered':registered})


def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username','')
        password = request.POST.get('password','')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('basic_app:news'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html')

basic_app/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Blue Chip Hoops</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/css/index.css' %}">
<!-- Javascript -->
<script
src="https://code.jquery.com/jquery-3.2.1.min.js"
integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
  $(document).ready(function() {
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top bg-ghost">
    <div class="container-fluid">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'basic_app:news' %}">News</a></li>
          <li><a href="{% url 'basic_app:my_recruits' %}">My Recruits</a></li>
          <li><a href="{% url 'basic_app:natl_rank' %}">National Rankings</a></li>
          <li><a href="{% url 'basic_app:upcoming' %}">Upcoming Events</a></li>
          <li><a href="{% url 'basic_app:manage_staff' %}">Manage Program</a></li>
          <li><a href="{% url 'basic_app:manage_social' %}">Social Media</a></li>
        </ul>
      </div>
    </div>
    </nav>

    {% block body_block %}
    <!-- Stuff in here is specific to that page -->
    {% endblock %}

  </body>
</html>

basic_app/templates/basic_app/base1.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Blue Chip Hoops</title>
    <!-- Stylesheets -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/css/index.css' %}">
    <!-- Javascript -->
    <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
      $(document).ready(function() {
        $('[data-toggle="tooltip"]').tooltip();
      });
    </script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top bg-ghost">
      <div class="container-fluid">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Blue Chip Hoops</a>
      </div>
        <div class="collapse navbar-collapse" id="navbar">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'basic_app:index' %}">Home</a></li>
            <li><a href="{% url 'basic_app:info' %}">Info</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a class="blue" href="{% url 'basic_app:signup' %}"><button type="button" name="button" class="button-primary" style="border-color: #1E47FF; border-radius: 5px; border: solid; max-width:100px; color: white;">Sign Up</button></a></li>
            <li><a class="denim" href="{% url 'basic_app:login' %}"><button type="button" name="button" class="button-primary" style="background-color:white; border-radius: 5px; border: solid; max-width:100px; border-color:#263DA5;">Sign In</button></a></li>
          </ul>
        </div>
      </div>
    </nav>
  </body>
  {% block body_block %}
  <!-- Stuff in here is specific to that page -->
  {% endblock %}
</html>

basic_app/templates/basic_app/index.html
{% extends 'basic_app/base1.html'%}
{% block body_block %}
<!-- {% load render_bundle from webpack_loader %} -->
<div class="container bg-denim tall" style="margin-top: 10rem; height: 650px; min-width: 400px; margin-bottom: 3rem;">
  <h1 class="heading ghost" style="margin-top: 5rem;">Welcome to Blue Chip Hoops</h1>
      <div class="login-banner" style="margin-top: 5rem;"></div>
      <div id="reactapp"></div>
    <form class="center form-primary" style="margin: auto; width: 53%; height: 10rem; position: relative; margin-top: -23rem;">
      <h2 class="ghost" style="padding-top: 12px;">Sign In</h2>

      <form action="{% url 'basic_app:index' %}" method="POST">
        {% csrf_token %}

        <p>
          <input class="bg-ghost" type="text" name="User Name" placeholder="Email Address">
        </p>
        <p>
          <input class="bg-ghost" type="password" name="Password" placeholder="Password">
        </p>
        <button type="button" name="login_btn" class="button button-primary ghost">Sign In</button>

      </form>

    </form>

<!-- {% render_bundle 'main' %} -->
</div>

{% endblock %}

basic_app/templates/basic_app/info.html
{% extends "basic_app/base1.html" %}
{% block body_block %}
<div class="container bg-ghost tall"style="margin-top: 10rem;">
  <h1 id="info_h1">Blue Chip Hoops</h1>
  <article>
    <h2>What is Blue Chip Hoops?</h2>
      <p class="content">Blue Chip Hoops was built to help baseketball coaches manage their
        programs better. We believe that coaches should use technology to keep up
        with recruits, current players, other coaches, and events in one simple
        place. </p>

    <h2>What Can Blue Chip Hoops Do For You?</h2>
      <p class="content">Blue Chips Hoops can help you manage contact with recruits, send
        automated news alerts about key recruits, monitor social media, compile
        schedules of upcoming events, and even boost your social media profile.</p>
    </article>
</div>

{% endblock %}

basic_app/templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base1.html" %}
{% block body_block %}

<div class="bg-ghost center container mxn2 mt4 pt4" style="margin-top: 10%;">
	<h1>Please Sign In</h1>
	<form action="{% url 'basic_app:login' %}" method="POST" style="padding: 10px;">
		{% csrf_token %}
		<input type="text" name="username" placeholder="username">
		<input type="password" name="password">
		<input class="bg-ghost button button-primary"type="submit" value="Sign In" style="border: solid; border-radius:5px; border-color: #263DA5;">
	</form>

</div>

{% endblock body_block %}

basic_app/templates/basic_app/my_recruits.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="container bg-ghost tall" style="margin-top: 10rem; width: 95%;">
  <h1>My Recruits</h1>
  <div style="overflow-x: auto;">
  <table class="bg-ghost table striped">
    <thead>
      <th>Name</th>
      <th>Position</th>
      <th>Height</th>
      <th>Weight</th>
      <th>High School</th>
      <th>State</th>
      <th>Phone Number</th>
      <th>Twitter</th>
      <th>Last Contacted</th>
      <th>Next Game</th>
    </thead>
    <tr>
      <td>Michael Jordan</td>
      <td>G</td>
      <td>6'5</td>
      <td>175</td>
      <td>Laney High School</td>
      <td>NC</td>
      <td>(555)123-4567</td>
      <td>@mj23</td>
      <td>8/11/1981</td>
      <td>8/15/1981</td>
      <td><span data-toggle="tooltip" data-placement="top" title="Remove player from list." class="delete glyphicon glyphicon-trash" id="delete_player"></span></td>
    </tr>
  </table>
  </div>
  <button class="button-primary" type="button" name="button" style="margin-bottom: 5px;">Add Recruit</button>
</div>
{% endblock %}

basic_app/templates/basic_app/natl_ranks.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="container bg-ghost tall"style="margin-top: 10rem; width: 95%;">
  <h1>National Rankings</h1>
  <div style="overflow-x: auto;">
  <table class="bg-ghost table striped">
    <thead>
      <th>Rivals Rank</th>
      <th>ESPN Rank</th>
      <th>Name</th>
      <th>Position</th>
      <th>High School</th>
      <th>Height</th>
      <th>Weight</th>
      <th>Schools</th>
    </thead>
    <tr>
      <td>1</td>
      <td>1</td>
      <td>Michael Jordan</td>
      <td>G</td>
      <td>Laney High School</td>
      <td>6'5</td>
      <td>175</td>
      <td><a href="#">List</a></td>
    </tr>
  </table>
</div>
</div>


{% endblock %}

basic_app/templates/basic_app/news.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="container bg-ghost tall"style="margin-top: 10rem;">
  <h1>Welcome Coach {Last Name}</h1>
  <h2>{School Name and Mascot}</h2>
    <div class="left_panel col-4">
      <h4>Staff</h4>
      <ul style="list-style:none; text-align:left; text-align:top;">
        <li>Dean Smith</li>
        <li>James Naismith</li>
        <li>John Wooden</li>
        <li>Adoph Rupp</li>
      </ul>
    </div>
    <div class="right_panel col-4">
      <h2>Twitter Updates</h2>
    </div>
    <div class="mid_panel col-4">
      <h1>News</h1>
      <h2><a href="#">ESPN: Greg Oden commits to Buckeyes...</a></h2>
      <h2><a href="#">LA Times: Bill Walton stays home...</a></h2>
      <h2><a href="#">Chicago Tribune: Isiah Thomas Going to Bloomington...</a></h2>
    </div>
</div>

{% endblock %}

basic_app/templates/basic_app/signup.html
{% extends "basic_app/base1.html" %}
{% block body_block %}
<div class="container bg-ghost tall" style="margin-top: 10rem">
    <h1>Sign Up</h1>

    <!-- <input type="text" name="first_name" placeholder="First Name">
    <p></p>
    <input type="text" name="last_name" placeholder="Last Name">
    <p></p>
    <input type="text" name="username" placeholder="Email Address">
    <p></p>
    <input type="password" name="user_pwd" placeholder="Password">
    <p></p>
    <input class="button button-primary ghost" type="submit" name="Sign In" value="Submit" style="margin-bottom: 15px;"> -->
    {% if registered %}
      <h1 class="heading denim">Thank you for registering</h1>
    {% else %}
      <form method="POST" enctype="multipart/form-data" style="padding: 5px;">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input class="button button-primary ghost" type="submit" value="Signup">
      </form>
    {% endif %}

</div>

<!-- <div class="jumbotron">
  {% if registered %}
  <h1>Thank your for registering!</h1>
  {% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the form:</h3>

  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">
  </form>
{% endif %}
</div> -->
{% endblock %}

basic_app/templates/basic_app/social.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="container bg-ghost tall"style="margin-top: 10rem;">

  <h1>Social Media</h1>
</div>

{% endblock %}

basic_app/templates/basic_app/staff.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="container bg-ghost tall"style="margin-top: 10rem; width: 95%;">
  <h1>Manage Staff</h1>
  <div style="overflow-x: auto;">
  <table class="bg-ghost table striped">
    <thead>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email Address</th>
      <th>Phone Number</th>
      <th>Active Since</th>
      <th>Twitter</th>
    </thead>
    <tr>
      <td>Dean</td>
      <td>Smith</td>
      <td>dmith@unc.edu</td>
      <td>(555)111-2222</td>
      <td>4/17/1960</td>
      <td>@coachdeansmith</td>
      <td><span data-toggle="tooltip" data-placement="top" title="Remove user." class="delete glyphicon glyphicon-trash" id="delete_user"></span></td>
    </tr>
  </table>
</div>
<button class="button-primary" style="margin-bottom: 0.5rem; color: #F9FAFF;">Add User</button>
</div>

{% endblock %}

basic_app/templates/basic_app/upcoming.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="container bg-ghost tall"style="margin-top: 10rem;">
  <h1>Upcoming Events</h1>

<iframe src="https://calendar.google.com/calendar/embed?src=6n9c5qnu4i4a9d2v5qtmo8fqj0%40group.calendar.google.com&ctz=America/Chicago" style="border: 0; margin-top: 2rem;" width="800" height="600" frameborder="0" scrolling="no"></iframe>

</div>
{% endblock %}